---
- hosts: all

  sudo: yes

  tasks:

  - name: Install ntpdate
    apt:
      name: ntpdate
      state: latest

  - copy:
      src: files/cron.ntpdate
      dest: /etc/cron.d/cron.ntpdate
      owner: root
      group: root
      mode: 0644
